# Module manifest for module 'TerminalSessions'
# Generated by: trackd
# Generated on: 2025-11-07

@{
    RootModule             = 'TerminalSessions.dll'
    ModuleVersion          = '0.0.2'
    CompatiblePSEditions   = @('Desktop', 'Core')
    PowerShellVersion      = '5.1'
    DotNetFrameworkVersion = '4.7.2'
    ClrVersion             = '4.0'
    GUID                   = '6d76a8aa-b182-43e0-9663-1e8f3e514614'
    Author                 = 'trackd'
    CompanyName            = 'Unknown'
    Copyright              = '(c) trackd. All rights reserved.'
    Description            = 'PowerShell module for managing Windows Remote Desktop Sessions.'
    TypesToProcess         = @(
        'TerminalSessions.Types.ps1xml'
    )
    FormatsToProcess       = @(
        'TerminalSessions.Format.ps1xml'
    )
    FunctionsToExport      = @()
    CmdletsToExport        = @(
        'Get-TerminalSession'
        'Get-TerminalInfo'
        'Get-TerminalClientInfo'
        'Remove-TerminalSession'
        'Send-TerminalMessage'
        'Disconnect-TerminalSession'
    )
    VariablesToExport      = @()
    AliasesToExport        = @(
        'Get-WTSSession'
        'Get-WTSInfo'
        'Get-WTSClientInfo'
        'Remove-WTSSession'
        'Send-WTSMessage'
        'Disconnect-WTSSession'
        'gts'
        'gtc'
        'gti'
        'rts'
        'sdtm'
        'dcts'
    )
    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()
    PrivateData            = @{
        PSData = @{
            Tags = @('RDS', 'WTS', 'TerminalServices', 'Windows','quser','qwinsta')
            # LicenseUri = ''
            ProjectUri = 'https://github.com/trackd/TerminalSessions'
            # IconUri = ''
            # ReleaseNotes = ''
            # Prerelease = ''
            # RequireLicenseAcceptance = $false
            # External dependent modules of this module
            # ExternalModuleDependencies = @()
        }
    }
    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''
}
